# Generated by Django 5.1.4 on 2024-12-13 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetic_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genetictest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Генетический тест', 'verbose_name_plural': 'Генетические тесты'},
        ),
        migrations.AlterField(
            model_name='genetictest',
            name='milk_yield',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Продуктивность должна быть положительным числом')]),
        ),
    ]
